AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 7

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
